### ISSUE TITLE
Wont detect decals_subrect.txt 

### ISSUE THREAD

**Issue by QuackCola** [rob5300/KVtoKV3Updater#1]
When directing the program to the decals_subrect.txt which in my case is one folder up from the updaters exe it fails to find it when its clearly there
![explorer_f9ZJ0LCnjh](https://user-images.githubusercontent.com/23345567/172939041-19049bc9-665d-4cd0-af13-7717ff4d9016.png)

**Comment by rob5300** [comment]
Does it work when you move the files to the same dir as the executable? I will look into this issue

**Comment by rob5300** [comment]
Please try v1.0.1 and see if the error message gives more help.

**Comment by QuackCola** [comment]
![WindowsTerminal_iWUIXoJohz](https://user-images.githubusercontent.com/23345567/172951944-4e1b4d09-81c7-41b7-986a-3ec737fceb2a.png)



files im using from L4D2
[surfaceproperties_manifest.txt](https://github.com/rob5300/KVSurfaceUpdater/files/8874208/surfaceproperties_manifest.txt)
[decals_subrect.txt](https://github.com/rob5300/KVSurfaceUpdater/files/8874209/decals_subrect.txt)

**Comment by rob5300** [comment]
Thanks I will try with these and fix the issue its causing

**Comment by QuackCola** [comment]
> Thanks I will try with these and fix the issue its causing

np let me know if you need anything else and ill get back to you as soon as i can.

**Comment by rob5300** [comment]
Should be fixed with the latest release: https://github.com/rob5300/KVSurfaceUpdater/releases/tag/v1.0.2

**Comment by QuackCola** [comment]
Works as expected, always love giving your tools hard time!
